### ISSUE TITLE
use

### ISSUE THREAD

**Issue by quan97it** [words/similar-english-words#2]
how to use it? i dont know !

**Comment by zeke** [comment]
Hi. This is a module that can be used with Node.js. Did you read the README? 

https://github.com/words/similar-english-words#readme

**Comment by quan97it** [comment]
When I enter a wrong word it will produce a list of correct words?  Do you
have a dictionary?  How do I use it when I have installed nodejs?  I am not
familiar with nodejs

Vào 2:32, Th 5, 7 thg 5, 2020 Zeke Sikelianos <notifications@github.com> đã
viết:

**Comment by wooorm** [comment]
We do expect you to know a bit about JavaScript and Node to use this project. See [nodejs.dev](https://nodejs.dev) for more information on Node.

If you’re familiar with JS and Node, then the readme provides the steps to take. See Install on how to install this package. See Use for an example that you can then put in a script (say, `example.js`), and run with Node (say, `node example.js`).

**Comment by wooorm** [comment]
Closing this, feel free to comment again if you need more help!
